<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-97HQ61N" name="testScripts.TestHome" tests="12" failures="1" timestamp="20 Aug 2018 18:55:57 GMT" time="747.273" errors="0">
  <testcase name="testHotel" time="67.692" classname="testScripts.TestHome"/>
  <testcase name="testFlight" time="64.563" classname="testScripts.TestHome"/>
  <testcase name="testHotelAndFlight" time="71.904" classname="testScripts.TestHome">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at testScripts.TestHome.testHotelAndFlight(TestHome.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testHotelAndFlight -->
  <testcase name="testCar" time="45.408" classname="testScripts.TestHome"/>
  <testcase name="testPckgdHolys" time="58.417" classname="testScripts.TestHome"/>
  <testcase name="testThngsToDo" time="57.766" classname="testScripts.TestHome"/>
  <testcase name="testCart" time="46.164" classname="testScripts.TestHome"/>
  <testcase name="testManage" time="59.282" classname="testScripts.TestHome"/>
  <testcase name="testRegtr" time="65.369" classname="testScripts.TestHome"/>
  <testcase name="testLogin" time="84.833" classname="testScripts.TestHome"/>
  <testcase name="testCall" time="43.622" classname="testScripts.TestHome"/>
  <testcase name="testLang" time="82.253" classname="testScripts.TestHome"/>
</testsuite> <!-- testScripts.TestHome -->
